### ISSUE TITLE
OSX Binary doesn't have execution permission

### ISSUE THREAD

**Issue by alebianco** [codearoni/zxp-provider#3]
The ZXPSignCmd binary for OSX is not executable.

```bash
$ curl -L https://github.com/codearoni/zxp-provider/archive/1.1.1.tar.gz | tar xv **/ZXPSignCmd -O > ZXPSignC
$ stat -f '%A %N' ZXPSignCmd
> 644 ZXPSignCmd
$ ./ZXPSignCmd
> -bash: ./ZXPSignCmd: Permission denied
```

Tested both the github release archive and the npm published package, same results with both.
Once changed the permissions to executable, it works as expected.

**Comment by codearoni** [comment]
Thanks for submitting the PR @alebianco 

Can you clarify as to what exactly you changed in the binary. Is this a new binary taken from CEP-Resources, or is it a modification of the existing bin.

**Comment by alebianco** [comment]
it's the least I could do

The binary is the same, I just changed the permissions from 644 to 755 so it can be executed

**Comment by codearoni** [comment]
I'll role a patch release hopefully this weekend. It's been a busy week...thanks again

**Comment by codearoni** [comment]
Sorry for the delay. Holidays and what not.

This fix was released with v1.1.2

Tagged, published, merged. Thx again for the PR.

**Comment by alebianco** [comment]
Tnx for the merge @codearoni 

Hate to be a pain, especially for xmas ... but something's still wrong in the npm package.

The two archives (.zip and .tar.gz) on the github releases page have the executable command as expected. The one installed from npm doesn't. Any idea why this happens?

It's progress I guess, but the issue isn't completely fixed yet 😢 🐼

**Comment by codearoni** [comment]
the bin property just add symlinks so you can make CLI modules with node. it's not meant or required for actually binaries like zxpSignCmd. 

I'm at a loss here, and I don't own a Mac. You're welcome to file another PR. You might have more luck forking this repo and publishing your own version of it to debug the issue.

**Comment by LazyChild** [comment]
@codearoni the execution permission is still missing on Mac OS X, if we install from npm.
I am guessing that you ran "npm publish" on a windows machine?
Is it okay to grant me the access? I can help publish it on a Mac.
Thanks!
